Add github native code scanning
pajbot/pajbot pull request #1045
Opened 2020-10-09 11:31 UTC by alazymeme

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

This implements githubs new code scanning stuff. By default, the workflow scans:

- Every push to the default branch
- Every pull request to the default branch
- The default branch at 3pm every Sunday

More information can be found below:
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/about-code-scanning
https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning

2020-10-09 19:19 UTC, RAnders00 requested changes

2020-10-09 19:19 UTC, RAnders00 commented on .github/workflows/codeql-analysis.yml
> +    #   make release
Remove autobuild since we dont need it

2020-10-09 19:19 UTC, RAnders00 commented on .github/workflows/codeql-analysis.yml
> +    - cron: '0 2 * * 5'
Add a comment that this means "3pm every Sunday"

2020-10-10 07:34 UTC, RAnders00 approved these changes

2020-10-10 07:39 UTC, RAnders00 commented
Is the CodeQL analyze going to run on every PR (and take so long)?

2020-10-10 07:42 UTC, pajlada approved these changes
:+1:

2020-10-10 07:44 UTC, merged

2020-10-10 08:03 UTC, alazymeme commented
> Is the CodeQL analyze going to run on every PR (and take so long)?

Yes - I can alternatively configure it so that it only runs on every push/weekly so it doesn't hold up the merging of prs?

2020-10-10 08:06 UTC, RAnders00 commented
It's fine since it's not set to be "required" to merge a pull request. As far as I understand it doesn't fail the status check either when the PR introduces a vulnerability, right?