Add preferred roulette command option
pajbot/pajbot pull request #1067
Opened 2020-10-30 07:26 UTC by alazymeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

2020-10-30 10:08 UTC, RAnders00 requested changes
Could you just make it a text setting? E.g. like here: https://github.com/pajbot/pajbot/blob/d0304c7433fead71f64438d7ff5d2da81bca0043/pajbot/modules/paidtimeout.py#L23-L31

2020-10-30 13:01 UTC, RAnders00 requested changes
You also need to make the examples dynamic, !roulette is currently hardcoded

2020-11-01 12:34 UTC, RAnders00 approved these changes

2020-11-01 13:15 UTC, pajlada approved these changes

2020-11-01 13:18 UTC, pajlada commented on pajbot/modules/roulette.py
> +            label="Command name (i.e. roulette)",
```suggestion
            label="Command name (e.g. roulette)",
```

2020-11-01 13:18 UTC, pajlada commented on pajbot/modules/roulette.py
> +            label="Command name (i.e. roulette)",
minor thing but pls accept this @alazymeme and I'll merge it

2020-11-01 21:27 UTC, pajlada approved these changes

2020-11-01 21:50 UTC, merged