Update variables doc to make a bit more sense
pajbot/pajbot pull request #1133
Opened 2021-01-17 10:30 UTC by alazymeme

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

Prior to work on variables, I didn't fully understand this document. I've changed it so it makes a lot more sense.

2021-01-17 10:31 UTC, alazymeme commented
Any chance someone could assist with the `add` and `slice` filters? I couldn't figure out what add does, slice I'm not 100% how to word to make it "easier" to understand.

2021-01-17 11:03 UTC, RAnders00 commented
add() interprets the input as a number and adds some other number to it. E.g. `$(datetime:Europe/Amsterdam|strftime(%W)|add(1)` gets next week's week-of-the-year number.

slice() is documented here: https://github.com/pajbot/pajbot/pull/812

2021-01-17 11:29 UTC, pajlada requested changes

2021-01-17 11:29 UTC, pajlada commented on docs/variables.md
> +`upper` - converts the variable all to uppercase\
rephrase to real english please

2021-01-17 11:29 UTC, pajlada commented on docs/variables.md
> +`or_broadcaster`/`or_streamer` - if nothing, return the streamer's name\
```suggestion
`or_broadcaster`/`or_streamer` - if the previous filter failed, return the streamer's name\
```

2021-01-17 11:29 UTC, pajlada commented on docs/variables.md
> +`or_else` - if nothing, return what is specified\
```suggestion
`or_else` - if the previous filter failed, return what is specified\
```

2021-01-17 11:29 UTC, pajlada commented on docs/variables.md
> +`urlencode` - replace spaces with a `+`\
```suggestion
`urlencode` - URL encodes the value. see https://en.wikipedia.org/wiki/Percent-encoding\
```

2021-01-17 11:29 UTC, pajlada commented on docs/variables.md
> +`slice` - ????
```suggestion
`slice` - slice the string like a python3 string - see https://www.digitalocean.com/community/tutorials/how-to-index-and-slice-strings-in-python-3 (NOTE: We don't support what they call 'stride')
```

2021-01-23 12:17 UTC, pajlada approved these changes

2021-01-23 12:18 UTC, merged