Fix incorrect usage examples
pajbot/pajbot pull request #1325
Opened 2021-06-30 17:28 UTC by zneix

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

Found this while browsing source out of boredom ;p

2021-06-30 18:47 UTC, RAnders00 approved these changes

2021-06-30 18:48 UTC, RAnders00 commented
Shouldn't there be a changelog entry? Even though it's extremely minor I don't see on what basis we shouldn't add one.

2021-06-30 18:48 UTC, RAnders00 requested changes
Shouldn't there be a changelog entry? Even though it's extremely minor I don't see on what basis we shouldn't add one.

2021-06-30 22:43 UTC, zneix commented
> Shouldn't there be a changelog entry? Even though it's extremely minor I don't see on what basis we shouldn't add one.

I just thought this is soooo minor and that nobody probably ever noticed this that realistically speaking there's no need for a changelog entry, but since this isn't Chatterino where there're releases made after every 150+ changelog entries I might as well include one.

2021-07-02 08:43 UTC, pajlada approved these changes

2021-07-02 22:30 UTC, RAnders00 approved these changes

2021-07-02 22:30 UTC, merged