Added playsound admin logging
pajbot/pajbot pull request #1382
Opened 2021-08-06 09:37 UTC by ALazyMeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

Implements basic logging into the playsound module. Simple things like: adding playsound, editing playsound (without/with link) and removing playsound. I decided not to complicate it too much and risk flooding logs by someone adjusting the volume/cooldown, etc.

2021-08-06 11:22 UTC, RAnders00 requested changes
You should probably add admin logging for the web functionalities too, not just the commands: https://github.com/pajbot/pajbot/blob/master/pajbot/web/routes/api/playsound.py

2021-08-06 15:19 UTC, RAnders00 approved these changes
Looks good to me, waiting for @pajlada to test it first though, then he can merge it as far as I'm concerned.

2021-08-07 09:28 UTC, pajlada commented
I went ahead and complicated your edit entry so the changed values are listed; 
![image](https://user-images.githubusercontent.com/962989/128595725-83624d95-6fff-4c6c-b2de-74a4b18eaec3.png)

2021-08-07 09:28 UTC, pajlada approved these changes

2021-08-07 09:37 UTC, merged