Fix playsound module toggling from playsound admin page
pajbot/pajbot pull request #1825
Opened 2022-04-07 15:10 UTC by pajlada

- Fix toggling of playsound module from playsound admin page
- Add changelog entry

Not yet tested

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [ ] I have tested all changes

2022-04-07 21:40 UTC, TroyKomodo commented
Should toggling playsounds require you to click the save button?

2022-04-07 21:44 UTC, RAnders00 requested changes

2022-04-07 21:44 UTC, RAnders00 commented on static/scripts/admin/playsound.admin.js
> +                new_state: checked ? true : false,
`checked ? true : false`? Can’t that be simplified to just `checked`?

2022-04-07 21:52 UTC, pajlada commented
> Should toggling playsounds require you to click the save button?

Not really relevant for this PR

2022-04-07 21:54 UTC, pajlada commented
Tested this now and it works as expected :ok_hand:

2022-04-08 08:14 UTC, RAnders00 approved these changes

2022-04-08 08:15 UTC, merged