added the announcement message type
pajbot/pajbot pull request #1847
Opened 2022-04-16 17:25 UTC by mmattbtw

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [ ] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

2022-04-23 08:50 UTC, pajlada requested changes
Feature looks good to me, happy to add it. I think we should call it `announce` instead though, if that's something you can do just poke me when it's done and I'll review&merge this in. If not, let me know and I'll make those changes on your branch :+1: Thank you!

2022-04-23 08:50 UTC, pajlada commented on pajbot/bot.py
> +        self.say("/announce " + message[: CHARACTER_LIMIT - 4], channel=channel)
The `-4` from `def me` is to account for the characters that we prefix (`/me `), so for `/announce` we'd need to cut 10 characters instead
```suggestion
        self.say("/announce " + message[: CHARACTER_LIMIT - 10], channel=channel)
```

2022-04-24 13:27 UTC, pajlada commented on pajbot/utils/clean_up_message.py
> +permitted_commands = {"me", "announce"}
This list is for commands that we don't care if a user uses with user-input - changing a command from a normal privmsg to an action is fine, but using announce is too privileged

```suggestion
permitted_commands = {"me"}
```

2022-04-24 13:30 UTC, pajlada requested changes

2022-04-24 13:30 UTC, pajlada commented on templates/admin/create_command.html
> +		<option value="announce">Announce</option>
Use spaces instead of tabs

2022-04-24 13:30 UTC, pajlada commented on templates/admin/create_timer.html
> +		<option value="announce" {{ 'selected' if timer and timer.action.subtype == 'announce' else '' }}>Announce</option>
Use spaces instead of tabs

2022-04-25 10:29 UTC, ALazyMeme requested changes

2022-04-25 10:29 UTC, ALazyMeme commented on CHANGELOG.md
> +- Minor: Added the `announce` message type. (#1847)
Recent changelog entries should be added on top of the categorized list.

```suggestion
- Minor: Added the `announce` message type. (#1847)
- Minor: Set the ignore, admincommands, dbmanage & debug modules as hidden due to their un-toggleable and un-configurable nature. (#1835)
```

2022-04-25 10:29 UTC, ALazyMeme commented on pajbot/bot.py
> +            self.announce(message)
Announcements are announcements, they aren't to a specific user, but to the entire chat. I don't think this is appropriate in this function.

2022-04-28 07:44 UTC, ALazyMeme requested changes

2022-04-28 07:44 UTC, ALazyMeme commented on pajbot/modules/quest.py
> +            options=["say", "whisper", "me", "announce", "reply"],
Wouldn't be a good idea for this command
```suggestion
            options=["say", "whisper", "me", "reply"],
```

2022-04-28 07:44 UTC, ALazyMeme commented on pajbot/modules/quest.py
> +            options=["say", "whisper", "me", "announce", "reply"],
Neither this command
```suggestion
            options=["say", "whisper", "me", "reply"],
```

2022-04-30 09:42 UTC, pajlada approved these changes

2022-04-30 09:43 UTC, ALazyMeme approved these changes
yep

2022-04-30 09:43 UTC, merged