Add customizable messages to paidtimeout module
pajbot/pajbot pull request #1848
Opened 2022-04-18 02:38 UTC by ALazyMeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

2022-04-18 02:39 UTC, ALazyMeme commented
I need to make the commands page dynamic. Obviously it shouldn't show anything if the messages are blank. What is the best way of going about this? Seems to be the last thing I need in order to complete the pr.

2022-04-24 09:49 UTC, pajlada requested changes

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                        chat=f"user:!{self.settings['command_name2']} karl_kons\nbot>user: {self.settings['message_to_additional_timeouter'].format(victim='karl_kons', cost=self.settings['cost'], dur
use `get_phrase` instead of running `.format` on the setting

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                    chat=f"user:!{self.settings['command_name']} karl_kons\nbot>user: {self.settings['message_to_additional_timeouter'].format(victim='karl_kons', cost=self.settings['cost'], duration
use `get_phrase` instead of running `.format` on the setting

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                        self.settings["message_to_victim"].format(source=source, duration=_time),
use `get_phrase` instead of running `.format` on the setting

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                        self.settings["message_to_timeouter"].format(victim=victim, cost=_cost, duration=_time),
use `get_phrase` instead of running `.format` on the setting

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                        self.settings["message_to_additional_timeouter"].format(
use `get_phrase` instead of running `.format` on the setting

2022-04-24 09:49 UTC, pajlada commented on pajbot/modules/paidtimeout.py
> +                        self.settings["additional_message_to_victim"].format(source=source, duration=_time),
use `get_phrase` instead of running `.format` on the setting

2022-04-24 11:33 UTC, ALazyMeme commented
@pajlada Maybe I'm missing something, but the example you provided on stream doesn't seem to sufficiently cover the fact that there are 2 commands. Should I split it into example1 and example2 variables? Keep in mind there there are different timeout values and costs (1 for each command).

![image](https://user-images.githubusercontent.com/12804673/164974436-a4a8f38b-176c-46c3-9e08-d807ae811e66.png)

2022-08-14 03:40 UTC, closed without merging