Migrate `delete or timeout` function to bot class
pajbot/pajbot pull request #1872
Opened 2022-04-25 10:02 UTC by ALazyMeme

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [ ] I have tested all changes

2022-04-25 10:26 UTC, RAnders00 requested changes

2022-04-25 10:26 UTC, RAnders00 commented on pajbot/bot.py
> +            log.warning("Cannot use the Delete moderation_action if msg_id is None!!!! BabyRage")
lol. But I'd rather you throw an exception here

2022-04-25 10:26 UTC, RAnders00 commented on pajbot/bot.py
> +            if disable_warnings is True:
```suggestion
            if disable_warnings:
```

2022-04-25 10:26 UTC, RAnders00 commented on pajbot/bot.py
> +            log.warning("moderation_action must only equal Delete or Timeout.")
I'd rather you throw an exception here

2022-04-25 10:48 UTC, ALazyMeme commented
Will test once initial code is approved.

2022-04-25 20:35 UTC, RAnders00 requested changes
I was thinking like this

2022-04-25 20:35 UTC, RAnders00 commented on pajbot/bot.py
> +            return
```suggestion
            raise ValueError("moderation_action must only equal Delete or Timeout!")
```

2022-04-25 20:35 UTC, RAnders00 commented on pajbot/bot.py
> +            return
```suggestion
            raise ValueError("Cannot use the Delete moderation_action if msg_id is None!")
```

2022-04-26 11:11 UTC, RAnders00 commented
I‘d like to get @pajlada‘s opinion on this, I‘m not a super huge fan but it‘s alrighg

2022-04-26 11:33 UTC, ALazyMeme commented
> I‘m not a super huge fan

Why's that? The idea is mostly just to centralize the function i/o creating it in every module we want to use it in.

2022-04-30 09:59 UTC, pajlada approved these changes

2022-04-30 10:12 UTC, merged