Added `addcount` & `delcount` variables
pajbot/pajbot pull request #1913
Opened 2022-05-08 10:36 UTC by ALazyMeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

This worked and is quite scuffed

2022-05-08 11:25 UTC, pajlada requested changes

2022-05-08 11:25 UTC, pajlada commented on docs/variables.md
> +- `$(remcount:br_wins)` will remove 1 count from the br_wins counter
Add documentation to right below `$(kvi)`

2022-05-08 11:25 UTC, pajlada commented on pajbot/bot.py
> +    def add_count_value(self, key, extra={}):
Rename to `increment_kvi_value` and move to below `get_kvi_value`

2022-05-08 11:25 UTC, pajlada commented on pajbot/bot.py
> +    def del_count_value(self, key, extra={}):
Rename to `decrement_kvi_value` and move to below `get_kvi_value`

2022-05-08 11:25 UTC, pajlada commented on pajbot/models/action.py
> +        method_mapping["delcount"] = bot.del_count_value
Rename to `increasekvi`/`decreasekvi` and move to below `kvi`

Feel free to add `inckvi` and `incrementkvi` and `deckvi` and `decrementkvi` as aliases

2022-05-09 10:24 UTC, RAnders00 commented
What exactly is the use case of this?

2022-05-09 10:51 UTC, ALazyMeme commented
> What exactly is the use case of this?

Replacement of the `add_win`/`remove_win` functions, but also a count variable - which could be used for wins, literally anything that you can count.

2022-05-09 12:19 UTC, RAnders00 requested changes

2022-05-14 10:55 UTC, Felanbird commented on docs/variables.md
> +- `$(increasekvi:br_wins)`/`$(inckvi:br_wins)` will add 1 count to the br_wins counter
We discussed this on stream last week, and came to the conclusion that `increment` & `decrement` while correct, are not common enough words to actually get their point across. 
![image](https://user-images.githubusercontent.com/41973452/168422714-b24592aa-ff6f-4d20-be41-1d6f6ea13766.png)


[He said something about adding a space to the variable so they can have set values to something other than 1, (idk I forgot honestly) but it was said as a response to the wording issue].

2022-05-14 13:30 UTC, ALazyMeme commented on docs/variables.md
> +- `$(increasekvi:br_wins)`/`$(inckvi:br_wins)` will add 1 count to the br_wins counter
> He said something about adding a space to the variable so they can have set values to something other than 1

Said he would add it in a later pr

2022-05-15 10:13 UTC, RAnders00 requested changes

2022-05-15 10:13 UTC, RAnders00 commented on pajbot/bot.py
> +    def increase_kvi_value(self, key, extra={}):
Could you add typing info for `key`?

2022-05-15 10:13 UTC, RAnders00 commented on pajbot/bot.py
> +    def decrease_kvi_value(self, key, extra={}):
Same here

2022-05-15 11:45 UTC, pajlada commented on pajbot/bot.py
> +    def increase_kvi_value(self, key, extra={}):
Typing + return values added to both!

2022-05-15 11:46 UTC, pajlada commented
`$(increasekvi)` and `$(decreasekvi)` now allow you to increase or decrease the counter by a specified amount by using the syntax `$(increasekvi:KEYNAME<space>AMOUNT)` - there's some tests adding for the parsing function under `pajbot/tests/test_kvi.py`

2022-05-15 11:50 UTC, pajlada approved these changes
Tested this and it works as expected, documentation updated to reflect new functionality but would like one more person to check off on it ofc

2022-05-15 12:12 UTC, ALazyMeme commented
> Tested this and it works as expected, documentation updated to reflect new functionality but would like one more person to check off on it ofc

I tried testing it, but I couldn't figure out the merging errors I was getting ![image](https://user-images.githubusercontent.com/12804673/168472124-9f738c60-701c-4d0c-8ab0-edad2d947532.png)
I'll leave @RAnders00 to take a look.

2022-05-21 05:59 UTC, RAnders00 approved these changes

2022-05-21 08:18 UTC, merged