Move LastFM module to reply response type
pajbot/pajbot pull request #2118
Opened 2022-09-10 14:17 UTC by ALazyMeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [ ] I have tested all changes

2022-09-10 23:01 UTC, pajlada requested changes
Missing changelog entry

2022-09-10 23:27 UTC, ALazyMeme commented on pajbot/modules/lastfm.py
> +                    f"bot: {self.settings['current_song'].format(streamer=StreamHelper.get_streamer(), song='Adele - Hello')}",
Since we don't offer `{streamer}` anymore, I've just hardcoded pajlada as the user.

2022-09-11 09:03 UTC, pajlada requested changes

2022-09-11 09:03 UTC, pajlada commented on pajbot/modules/lastfm.py
> +                    f"@pajlada bot: {self.settings['current_song'].format(streamer=StreamHelper.get_streamer(), song='Adele - Hello')}",
`bot: @user {...`

2022-09-11 10:37 UTC, pajlada approved these changes

2022-09-11 10:43 UTC, pajlada commented
Tested this, works as expected :+1:

2022-09-11 10:43 UTC, merged