Refactor Helix subscriber fetching
pajbot/pajbot pull request #2203
Opened 2022-10-27 11:29 UTC by ALazyMeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [ ] I have tested all changes

2022-10-27 20:25 UTC, RAnders00 requested changes
Looks good otherwise as far as I can tell! Thank you!

2022-10-27 20:25 UTC, RAnders00 commented on CHANGELOG.md
> +- Dev: Improved Helix subscriber fetching to utilize the existing data provided by the Helix response. (#2203)
```suggestion
- Minor: Increased efficiency and speed of subscriber status refresh. (#2203)
```

2022-10-28 11:32 UTC, RAnders00 approved these changes

2022-10-28 15:29 UTC, pajlada commented
Running into this issue where the streamer can appear twice in the endpoint, not sure why this would happen since we should do a `list(set(...))`, needs some more investigation

```
Logging an uncaught exception (ActionQueue)
Traceback (most recent call last):
  File "/home/pajlada/git/pajbot/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "/home/pajlada/git/pajbot/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 1000, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "subscribers_pkey"
DETAIL:  Key (id)=(11148817) already exists.
```

2022-10-28 15:33 UTC, pajlada requested changes
^

2022-10-28 20:21 UTC, RAnders00 commented
I see the issue. I *assumed* we had this already because I assumed an equality comparison on two `UserBasics` objects would have already been used somewhere else in the code base, but we don‘t have equality and hash implemented for `UserBasics`.

https://github.com/pajbot/pajbot/blob/6b7681f29ce0f4bdb82d22bf44863c091c312094/pajbot/models/user.py#L42
https://stackoverflow.com/a/2909119

As a result of the hash function not being implemented, `set()` is not able to eliminate duplicates.

2022-10-28 20:25 UTC, RAnders00 commented
Also, I‘d like to argue that the fetcher function could very well return sets already. It‘s quite wasteful to turn list into set and back into list. If we directly used sets all the way (in the `_fetch_all_pages` method and in the `_fetch_X_page` method) we wouldn‘t need to do this. A conversion back to list is probably never necessary (after all, there‘s no inherent order to the list of subs.)

2022-10-29 15:20 UTC, RAnders00 approved these changes

2022-10-29 15:20 UTC, RAnders00 commented on pajbot/apiwrappers/twitch/helix.py
> +        return subscribers
```suggestion
        return set(subscribers)
```

2022-10-29 15:20 UTC, RAnders00 commented on pajbot/apiwrappers/twitch/helix.py
> +        subscribers = list(set(subscribers))
```suggestion
```

2022-10-29 15:20 UTC, RAnders00 commented
Oops, I didn‘t mean to select „Approve“, consider it a „Changes requested“, please.

2022-10-30 19:49 UTC, pajlada approved these changes
Works as expected

Old: `SubscriberFetchModule::_update_subscribers function took 4342.029 ms`
New: `SubscriberFetchModule::_update_subscribers function took 1413.810 ms`

:+1:

2022-10-30 19:50 UTC, merged

2022-10-31 02:57 UTC, RAnders00 commented on pajbot/apiwrappers/twitch/helix.py
> +    def fetch_all_subscribers(self, broadcaster_id: str, authorization) -> Set[UserBasics]:
The function does not actually return a set!!