Fix playsounds tab visibility on the admin page when the module was disabled
pajbot/pajbot pull request #2469
Opened 2023-05-25 16:13 UTC by hotbear1110

The "playsounds" menu tab is now always visible on the admins page.

I think this makes sense, since it would be nice to be able to edit the playsounds, without having to enable the module first.

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

2023-05-25 18:32 UTC, RAnders00 requested changes

2023-05-25 18:32 UTC, RAnders00 commented on CHANGELOG.md
> +- Bugfix: Fix playsounds MenuItem not being vissible on the admin page, when the module was disabled. (#2469)
```suggestion
- Bugfix: Fix playsounds tab in the top navigation bar not being visible on the admin page when the module was disabled. (#2469)
```

2023-05-26 12:47 UTC, pajlada approved these changes

2023-05-26 19:35 UTC, RAnders00 approved these changes

2023-05-26 19:35 UTC, merged

2023-05-26 19:35 UTC, RAnders00 commented
Thank you!